name: Node.js CI

on:
  push:
    branches: [ main ] # Trigger the workflow on every commit to the main branch.
  pull_request:
    branches: [ main ] # Trigger the workflow on pull requests targeting the main branch.

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Step 1: Check out the source code from the repository.

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Step 2: Use npm caching for faster dependency installs.

    - name: Install Node.js dependencies
      run: npm install --legacy-peer-deps # Step 3: Perform a clean install of Node.js dependencies.

    - name: Run tests
      run: npm run test # Step 4: Run tests using the specified Node.js version.
    # build and test the apps     
    - name: Build Backend
      run: |
        npm run build
        npm run test